import type { IconThemeMeta } from './types'

/*
  VSCode Icons（vscode-icons-team，MIT）。图标名是 @iconify-json/vscode-icons 里的名字，
  文件是 file-type-*，目录是 folder-type-*（展开加 -opened），
  由 scripts/build-icon-themes.mjs 抽成 sets/vscode-icons.json。
*/

const folderNames: Record<string, string> = {
  src: 'folder-type-src', source: 'folder-type-src',
  lib: 'folder-type-library', libs: 'folder-type-library',
  dist: 'folder-type-dist', build: 'folder-type-dist', out: 'folder-type-dist', output: 'folder-type-dist',
  test: 'folder-type-test', tests: 'folder-type-test', __tests__: 'folder-type-test', spec: 'folder-type-test',
  e2e: 'folder-type-e2e',
  public: 'folder-type-public', static: 'folder-type-public', www: 'folder-type-www',
  docs: 'folder-type-docs', doc: 'folder-type-docs',
  config: 'folder-type-config', configs: 'folder-type-config', '.config': 'folder-type-config',
  scripts: 'folder-type-script', script: 'folder-type-script',
  assets: 'folder-type-asset', asset: 'folder-type-asset',
  components: 'folder-type-component', component: 'folder-type-component',
  utils: 'folder-type-tools', util: 'folder-type-tools', utilities: 'folder-type-tools', tools: 'folder-type-tools',
  helpers: 'folder-type-helper', helper: 'folder-type-helper',
  hooks: 'folder-type-hook', hook: 'folder-type-hook',
  types: 'folder-type-typings', typings: 'folder-type-typings', '@types': 'folder-type-typings',
  node_modules: 'folder-type-node',
  '.git': 'folder-type-git', '.github': 'folder-type-github', '.vscode': 'folder-type-vscode',
  images: 'folder-type-images', image: 'folder-type-images', img: 'folder-type-images', icons: 'folder-type-images',
  styles: 'folder-type-style', style: 'folder-type-style', css: 'folder-type-css', scss: 'folder-type-sass',
  fonts: 'folder-type-fonts', font: 'folder-type-fonts',
  tmp: 'folder-type-temp', temp: 'folder-type-temp',
  api: 'folder-type-api', app: 'folder-type-app',
  views: 'folder-type-view', view: 'folder-type-view', pages: 'folder-type-view', page: 'folder-type-view',
  i18n: 'folder-type-locale', locales: 'folder-type-locale', locale: 'folder-type-locale', lang: 'folder-type-locale',
  shared: 'folder-type-shared', common: 'folder-type-common',
  server: 'folder-type-server', client: 'folder-type-client',
  plugins: 'folder-type-plugin', plugin: 'folder-type-plugin',
  middleware: 'folder-type-middleware', middlewares: 'folder-type-middleware',
  routes: 'folder-type-route', router: 'folder-type-route', routers: 'folder-type-route',
  controllers: 'folder-type-controller', controller: 'folder-type-controller',
  db: 'folder-type-db', database: 'folder-type-db',
  mock: 'folder-type-mock', mocks: 'folder-type-mock', __mocks__: 'folder-type-mock',
  coverage: 'folder-type-coverage', docker: 'folder-type-docker',
  template: 'folder-type-template', templates: 'folder-type-template',
  theme: 'folder-type-theme', themes: 'folder-type-theme',
  json: 'folder-type-json', packages: 'folder-type-package',
  models: 'folder-type-model', model: 'folder-type-model',
  modules: 'folder-type-module', services: 'folder-type-services',
  interfaces: 'folder-type-interfaces', include: 'folder-type-include',
  log: 'folder-type-log', logs: 'folder-type-log',
  '.claude': 'folder-type-claude',
}

const folderNamesExpanded = Object.fromEntries(
  Object.entries(folderNames).map(([k, v]) => [k, `${v}-opened`])
)

export const vscodeIcons: IconThemeMeta = {
  id: 'vscode-icons',
  label: 'VSCode Icons',
  render: 'svg',
  rules: {
    file: 'default-file',
    folder: 'default-folder',
    folderExpanded: 'default-folder-opened',
    rootFolder: 'default-root-folder',
    rootFolderExpanded: 'default-root-folder-opened',
    fileNames: {
      'package.json': 'file-type-npm', 'package-lock.json': 'file-type-npm', '.npmrc': 'file-type-npm',
      '.nvmrc': 'file-type-node', '.node-version': 'file-type-node',
      'pnpm-lock.yaml': 'file-type-pnpm', 'pnpm-workspace.yaml': 'file-type-pnpm',
      'yarn.lock': 'file-type-yarn', '.yarnrc': 'file-type-yarn', '.yarnrc.yml': 'file-type-yarn',
      'tsconfig.json': 'file-type-tsconfig', 'tsconfig.node.json': 'file-type-tsconfig',
      'tsconfig.app.json': 'file-type-tsconfig', 'tsconfig.base.json': 'file-type-tsconfig', 'jsconfig.json': 'file-type-tsconfig',
      '.gitignore': 'file-type-git', '.gitattributes': 'file-type-git', '.gitmodules': 'file-type-git',
      '.editorconfig': 'file-type-editorconfig',
      'license': 'file-type-license', 'license.md': 'file-type-license', 'license.txt': 'file-type-license',
      'dockerfile': 'file-type-docker', 'docker-compose.yml': 'file-type-docker', 'docker-compose.yaml': 'file-type-docker', '.dockerignore': 'file-type-docker',
      '.env': 'file-type-dotenv', '.env.local': 'file-type-dotenv', '.env.example': 'file-type-dotenv',
      '.env.development': 'file-type-dotenv', '.env.production': 'file-type-dotenv',
      'vite.config.ts': 'file-type-vite', 'vite.config.js': 'file-type-vite', 'vite.config.mts': 'file-type-vite', 'vite.config.mjs': 'file-type-vite',
      'vitest.config.ts': 'file-type-vitest', 'vitest.config.js': 'file-type-vitest', 'vitest.config.mts': 'file-type-vitest',
      'jest.config.js': 'file-type-jest', 'jest.config.ts': 'file-type-jest', 'jest.config.mjs': 'file-type-jest',
      '.prettierrc': 'file-type-prettier', '.prettierrc.json': 'file-type-prettier', '.prettierignore': 'file-type-prettier',
      'prettier.config.js': 'file-type-prettier', 'prettier.config.mjs': 'file-type-prettier',
      '.eslintrc': 'file-type-eslint', '.eslintrc.json': 'file-type-eslint', '.eslintrc.js': 'file-type-eslint', '.eslintignore': 'file-type-eslint',
      'eslint.config.js': 'file-type-eslint', 'eslint.config.mjs': 'file-type-eslint', 'eslint.config.ts': 'file-type-eslint',
    },
    fileExtensions: {
      js: 'file-type-js', mjs: 'file-type-js', cjs: 'file-type-js',
      jsx: 'file-type-reactjs',
      ts: 'file-type-typescript', mts: 'file-type-typescript', cts: 'file-type-typescript',
      tsx: 'file-type-reactts',
      'd.ts': 'file-type-typescriptdef', 'd.mts': 'file-type-typescriptdef', 'd.cts': 'file-type-typescriptdef',
      'test.js': 'file-type-testjs', 'spec.js': 'file-type-testjs', 'test.mjs': 'file-type-testjs',
      'test.ts': 'file-type-testts', 'spec.ts': 'file-type-testts', 'test.mts': 'file-type-testts',
      'test.jsx': 'file-type-testjs', 'spec.jsx': 'file-type-testjs', 'test.tsx': 'file-type-testts', 'spec.tsx': 'file-type-testts',
      'js.map': 'file-type-jsmap', 'mjs.map': 'file-type-jsmap', 'cjs.map': 'file-type-jsmap',
      json: 'file-type-json', jsonc: 'file-type-json', json5: 'file-type-json',
      html: 'file-type-html', htm: 'file-type-html',
      css: 'file-type-css', scss: 'file-type-scss', sass: 'file-type-scss', less: 'file-type-less',
      md: 'file-type-markdown', markdown: 'file-type-markdown', mdx: 'file-type-markdown',
      yml: 'file-type-yaml', yaml: 'file-type-yaml',
      xml: 'file-type-xml', svg: 'file-type-svg',
      sh: 'file-type-shell', bash: 'file-type-shell', zsh: 'file-type-shell',
      sql: 'file-type-sql',
      txt: 'file-type-text', log: 'file-type-log', env: 'file-type-dotenv',
      png: 'file-type-image', jpg: 'file-type-image', jpeg: 'file-type-image', gif: 'file-type-image',
      webp: 'file-type-image', ico: 'file-type-image', bmp: 'file-type-image', avif: 'file-type-image',
      woff: 'file-type-font', woff2: 'file-type-font', ttf: 'file-type-font', otf: 'file-type-font', eot: 'file-type-font',
      zip: 'file-type-zip', tar: 'file-type-zip', gz: 'file-type-zip', tgz: 'file-type-zip', '7z': 'file-type-zip', rar: 'file-type-zip',
      mp4: 'file-type-video', webm: 'file-type-video', mov: 'file-type-video',
      mp3: 'file-type-audio', wav: 'file-type-audio', ogg: 'file-type-audio', flac: 'file-type-audio',
    },
    languageIds: {
      javascript: 'file-type-js', typescript: 'file-type-typescript', json: 'file-type-json',
      html: 'file-type-html', css: 'file-type-css', scss: 'file-type-scss', less: 'file-type-less',
      markdown: 'file-type-markdown', yaml: 'file-type-yaml', xml: 'file-type-xml',
      shell: 'file-type-shell', sql: 'file-type-sql', plaintext: 'file-type-text',
    },
    folderNames,
    folderNamesExpanded,
  },
}
